'use client';

import React, { useEffect, useState } from 'react';
import { GraduationCap, CheckCircle2, Loader2, XCircle } from 'lucide-react';

export default function LearningsPage() {
  const [learnings, setLearnings] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { try { const response = await fetch('/api/learnings'); const json = await response.json(); if (!response.ok) throw new Error(json.error || 'Không thể tải learnings'); setLearnings(json.data || []); } catch (err) { setError(err instanceof Error ? err.message : 'Không thể tải learnings'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const decide = async (id: string, decision: 'confirmed' | 'rejected') => { try { const response = await fetch('/api/learnings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ learningId: id, decision, idempotencyKey: `learning-${id}-${decision}` }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || 'Không thể cập nhật learning'); setLearnings((current) => current.map((learning) => learning.id === id ? { ...learning, ...json.data } : learning)); } catch (err) { setError(err instanceof Error ? err.message : 'Không thể cập nhật learning'); } };
  return <div className="legacy-calm-page space-y-6 pb-12"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><div className="flex items-center gap-2"><GraduationCap size={22} className="text-indigo-600" /><h2 className="text-xl font-bold text-slate-900">Learnings (Kho bài học cá nhân)</h2></div><p className="mt-1 text-xs text-slate-500">Chỉ những bài học bạn xác nhận mới trở thành dữ liệu cho hành trình sau này.</p></div>{loading && <div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-indigo-600" /></div>}{error && <div className="rounded-2xl bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</div>}{!loading && !error && learnings.length === 0 && <div className="rounded-3xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">Chưa có bài học nào.</div>}<div className="grid grid-cols-1 gap-4 md:grid-cols-2">{learnings.map((learning) => <article key={learning.id} className="space-y-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><span className={`flex items-center gap-1 rounded-full px-2.5 py-0.5 text-[10px] font-bold ${learning.status === 'confirmed' ? 'bg-emerald-100 text-emerald-700' : learning.status === 'rejected' ? 'bg-slate-100 text-slate-500' : 'bg-amber-100 text-amber-700'}`}>{learning.status === 'confirmed' ? <CheckCircle2 size={12} /> : learning.status === 'rejected' ? <XCircle size={12} /> : null}{learning.status}</span><span className="text-[10px] text-slate-400">{new Date(learning.created_at).toLocaleDateString('vi-VN')}</span></div><p className="text-sm font-semibold leading-6 text-slate-800">“{learning.content}”</p>{learning.status === 'pending' && <div className="flex gap-2 border-t border-slate-100 pt-3"><button onClick={() => decide(learning.id, 'rejected')} className="rounded-xl border border-slate-200 px-3 py-2 text-[11px] font-semibold text-slate-600">Chưa đúng</button><button onClick={() => decide(learning.id, 'confirmed')} className="rounded-xl bg-emerald-600 px-3 py-2 text-[11px] font-semibold text-white">Đúng với mình</button></div>}</article>)}</div></div>;
}
